"""Agregamos Masa Grasa a models.py 

Revision ID: 34603422d700
Revises: 
Create Date: 2025-10-21 20:33:02.994705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34603422d700'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicion_corporal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('masa_grasa', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicion_corporal', schema=None) as batch_op:
        batch_op.drop_column('masa_grasa')

    # ### end Alembic commands ###
